base_model: yolov8n.pt
dataset_path: data/data.yaml
description: YOLO hyperparameter benchmark
fractions:
- 0.2
- 0.4
- 0.6
- 0.8
- 1.0
generate_plots: true
generate_report: true
max_batch_size: 32
max_epochs: 20
max_parallel_jobs: 1
max_time_hours: 1.0
memory_limit_gb: 8.0
model_size: m
name: yolo_benchmark
output_dir: results
repetitions: 3
save_checkpoints: false
save_models: true
seed: 42
selected_parameters:
- lr0
- batch
- epochs
- momentum
- weight_decay
- imgsz
- mosaic
- mixup
- degrees
- scale
test_split: test
track_gpu: true
track_memory: true
track_time: true
train_split: train
use_distributed: false
val_split: val
