# Default YOLO Hyperparameter Benchmark Configuration
# Based on UNIVERSIDADE PAULISTA Research

name: "yolo_hyperparameter_benchmark"
description: "Comprehensive YOLOv8m hyperparameter analysis based on research"

# Dataset Configuration
dataset_path: "data/coco128.yaml"
train_split: "train"
val_split: "val"
test_split: "test"

# Model Configuration
base_model: "yolov8m.pt"
model_size: "m"

# Benchmark Parameters
fractions:
  - 0.2   # 20% of parameter range
  - 0.4   # 40% of parameter range
  - 0.6   # 60% of parameter range
  - 0.8   # 80% of parameter range
  - 1.0   # 100% of parameter range

selected_parameters:
  # Learning parameters
  - lr0
  - lrf
  - momentum
  - weight_decay
  
  # Training configuration
  - batch
  - epochs
  - patience
  
  # Input processing
  - imgsz
  - hsv_h
  - hsv_s
  - hsv_v
  
  # Data augmentation
  - degrees
  - translate
  - scale
  - shear
  - perspective
  - flipud
  - fliplr
  - mosaic
  - mixup
  - copy_paste
  
  # Loss parameters
  - box
  - cls
  - dfl
  
  # NMS parameters
  - iou_thres
  - conf_thres

# Experimental Settings
repetitions: 3  # Number of repetitions per configuration
seed: 42        # Random seed for reproducibility

# Resource Limits
max_epochs: 100
max_batch_size: 32
memory_limit_gb: 8.0
max_time_hours: 24.0

# Output Configuration
output_dir: "results"
save_models: true
save_checkpoints: false
generate_plots: true
generate_report: true

# Performance Tracking
track_memory: true
track_time: true
track_gpu: true

# Parallel Processing
max_parallel_jobs: 1
use_distributed: false
